### ISSUE TITLE
Google Drive API change

### ISSUE THREAD

**Issue by dbietila** [Fordham-University-Libraries/G-CDL#15]
I received an email from Google this morning regarding an upcoming Drive API change.

> Items that have a Drive API permission with type=domain or type=anyone, where withLink=true (v2) or allowFileDiscovery=false (v3), will be affected by this security update.

> In addition to the item ID, your application may now also need a resource key to access these items. Without a resource key, requests for these items may result in a 404 Not Found error (See below for details). Note that access to items that are directly shared with the user or group are not affected.

Is this something that is likely to disrupt G-CDL?

**Comment by witt** [comment]
got it too, it should not, but let me confirm.

**Comment by witt** [comment]
confirmed that G-CDL app is not affected. The app only set permission of type = 'user' when sharing pdf tp a specific user. https://developers.google.com/drive/api/v3/reference/permissions
